spring:
  application:
    name: speedrun

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ecommerce
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create   # esta opci√≥n permite que el SQL se ejecute antes
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:products.sql

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081
