spring:
  application:
    name: speedrun

server:
  port: 8081

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ecommerce
    username: sa
    password:

sql:
  init:
    mode: always
    data-locations: classpath:products.sql

  h2:
    console:
      enabled: true     # Habilita la consola web
      path: /h2-console # URL: http://localhost:8080/h2-console

jpa:
  defer-datasource-initialization: ture


